-- Generated By: MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `pharmacy` ;

-- -----------------------------------------------------
-- Table `pharmacy`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`product_type` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`manufacturer` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`product` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  `composition` VARCHAR(45) NOT NULL,
  `unit_price` DECIMAL(8,2) NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_1_idx` (`product_type_id` ASC),
  INDEX `fk_product_2_idx` (`manufacturer_id` ASC),
  CONSTRAINT `fk_product_1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `pharmacy`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_2`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `pharmacy`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`customer` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(13) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`sales` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_sales_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pharmacy`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`doctor` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `crm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`product_purchased`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`product_purchased` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`product_purchased` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `sales_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_purchased_1_idx` (`sales_id` ASC),
  INDEX `fk_product_purchased_2_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_purchased_1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `pharmacy`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_purchased_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `pharmacy`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`medical_prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`medical_prescription` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`medical_prescription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prescription` VARCHAR(100) NOT NULL,
  `product_purchased_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medical_prescription_1_idx` (`product_purchased_id` ASC),
  INDEX `fk_medical_prescription_2_idx` (`doctor_id` ASC),
  CONSTRAINT `fk_medical_prescription_1`
    FOREIGN KEY (`product_purchased_id`)
    REFERENCES `pharmacy`.`product_purchased` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_prescription_2`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `pharmacy`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
